= WebSockets with Java/JEE Playground project

WebSockets with Java/JEE Playground project

[ TOC ]

== Disclaimer
Current source code and version is published without license. +
If you (somebody) want to use this in his project please contact me.
Afterwards I will grant the use of this code without warranty.
When I find some time to inform myself about the different possible licenses at link:http://choosealicense.com[choosealicense.com]
I will probably change to a suitable license.

== General information
This `WebSockets Playground` project is just a playground for my personal JEE samples which I use to test/play around with WebSockets.


== Technical information
  * The release versions are based on link:http://semver.org[Semantic Versioning 2.0.0].
  * The latest release require `JavaEE 7` (or newer) and is build with link:https://maven.apache.org[Maven] (version `3.3.x`).
  * Server tested (and working) with `Payara 4.1` and `Wildfly 11`
  * Client tested (and working) with `TomEE 7` and `Wildfly 11`

=== Server part

WebSocket is available via `ws://localhost:8080/pg-ws-server/motd` if deployed in (default) `Payara` server.

===  Client part

Client try to connect to server via WebSocket URI `ws://localhost:8080/pg-ws-server/motd` and publish a REST endpoint at `.../client/motds` and `.../client/motds/latest` (e.g. deploy locally on Tomcat with port `8082`: `http://localhost:8082/client/motds`).

== Current Features _(for this branch)_

  * NONE

== New and Noteworthy

  * *nothing*

== Roadmap

  * *none*

== Helpful...

=== Links

  * Nothing yet

=== Presentation

  * Nothing yet
